spring:
  application:
    name: companies-curd-fallback
server:
  servlet:
    context-path: /companies-curd-fallback
  port: 8787

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
