spring:
  datasource:
    username: debuggeandoideas
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/companies
    password: udemy
  application:
    name: companies-crud
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /companies-crud
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
