spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/companies
    username: debuggeandoideas
    password: udemy
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /companies-crud
  port: 8081

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
